process.env.MONGODB_URI ??= 'mongodb://localhost:27017'
process.env.MONGODB_DB_NAME ??= 'mostro-test'
process.env.OPENROUTER_API_KEY ??= 'test-key'
process.env.TELEGRAM_BOT_USERNAME ??= 'mostro_test_bot'
process.env.TELEGRAM_BOT_TOKEN ??= 'test-token'
process.env.TELEGRAM_WEBHOOK_SECRET_TOKEN ??= 'test-secret'
process.env.GMAIL_MAILER_CLIENT_ID = 'test-client-id'
process.env.GMAIL_MAILER_CLIENT_SECRET = 'test-client-secret'
process.env.GMAIL_MAILER_REFRESH_TOKEN = 'test-refresh-token'
process.env.GMAIL_MAILER_SENDER = 'bot@example.com'
// Direct assignment, not `??=`: the tests assert against these values. With `??=`
// the real .env overrides them, the result depends on the machine and the case data
// ends up printed in the CI log.
process.env.PATIENT_NAME = 'Juana Quintana'
process.env.DELIVERY_ADDRESS = 'Calle Falsa 123, Springfield'
process.env.REQUESTER_NAME = 'Francisca Boloños'
process.env.REQUESTER_PHONE = '555-3039'
process.env.DIAPERS_EMAIL_TO = 'panales@proveedor.test'
process.env.MEDS_EMAIL_TO = 'farmacia@proveedor.test'
process.env.REFUNDS_EMAIL_TO = 'reintegros@proveedor.test'
