// Generates the OpenUI Lang system prompt as a TS module.
//
// We emit .ts rather than .txt on purpose: `mastra build` bundles the server and
// doesn't copy loose assets, so a runtime readFileSync would break in
// production. As a module, the prompt ships inside the bundle.
//
// Run after touching the library: `pnpm generate:openui-prompt`.
import { writeFileSync } from 'node:fs'
import { openuiChatLibrary, openuiChatPromptOptions } from '@openuidev/react-ui/genui-lib'

const OUT = 'src/mastra/generated/openui-system-prompt.ts'

const prompt = openuiChatLibrary.prompt(openuiChatPromptOptions)

if (!prompt.includes('openui-lang')) {
    throw new Error('El prompt generado no menciona openui-lang: revisá la library antes de commitear.')
}

const file = `// GENERATED by scripts/generate-openui-prompt.ts — do not edit by hand.
// Regenerate with: pnpm generate:openui-prompt
export const OPENUI_SYSTEM_PROMPT = ${JSON.stringify(prompt)}
`

writeFileSync(OUT, file)
console.log(`Escrito ${OUT} (${prompt.length} bytes de prompt)`)
